env: flex
runtime: custom
# vm: true
api_version: 1
module: default

handlers:
- url: /
  static_files: client/dist/index.html
  upload: client/dist/index.html

- url: /
  static_dir: client/dist
# manual_scaling:
#   instances: 1

# handlers:
# - url: /(.*\.(html|css|js))
#   static_files: client/dist
#   upload: static/(.*\.(html|css|js))

# - url: /
#   static_files: client/dist/index.html
#   upload: static/index.html

# - url: /.*
#   script: client/src/app.js